version: '3.9'

services:
  input-service:
    build:
      context: ./input-service/app
    container_name: input-service
    env_file:
      - ./input-service/app/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./input-service:/app

  analysis-service:
    build:
      context: ./smartcontract-analysis
    container_name: analysis-service
    env_file:
      - ./smartcontract-analysis/.env
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - ./smartcontract-analysis:/app

