version: '3.9'

services:
  input-service:
    build:
      context: ./input-service/app
    container_name: input-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
